//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsEnvLoader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsEnvLoader.ProgramResources", typeof(ProgramResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*).
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting user environment variable &apos;{0}&apos;.
        /// </summary>
        internal static string DeletingUserEnvVar {
            get {
                return ResourceManager.GetString("DeletingUserEnvVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got empty JSON..
        /// </summary>
        internal static string GotEmptyJson {
            get {
                return ResourceManager.GetString("GotEmptyJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got no JSON to read..
        /// </summary>
        internal static string GotNoJson {
            get {
                return ResourceManager.GetString("GotNoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON files (*.json).
        /// </summary>
        internal static string JSONFiles {
            get {
                return ResourceManager.GetString("JSONFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Parse Error: {0}.
        /// </summary>
        internal static string JsonParseError {
            get {
                return ResourceManager.GetString("JsonParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet implemented..
        /// </summary>
        internal static string NotYetImplemented {
            get {
                return ResourceManager.GetString("NotYetImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON files (*.json)|*.json|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A JSON file that represents a simple key/value list without any nesting..
        /// </summary>
        internal static string ProgramArgJsonFile {
            get {
                return ResourceManager.GetString("ProgramArgJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple tool for setting user environment variables from a JSON file (eg. a user secrets file from Visual Studio)..
        /// </summary>
        internal static string ProgramDescription {
            get {
                return ResourceManager.GetString("ProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove given environment vars (irrespective of their values)..
        /// </summary>
        internal static string ProgramOptDelete {
            get {
                return ResourceManager.GetString("ProgramOptDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes to all aka. non-interactive mode. Do not ask before adding/deleting operations..
        /// </summary>
        internal static string ProgramOptYes {
            get {
                return ResourceManager.GetString("ProgramOptYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?\n [(Y)es/(N)o] (Default=Y).
        /// </summary>
        internal static string QuestionYesNo {
            get {
                return ResourceManager.GetString("QuestionYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading user environment variables from &quot;{0}&quot;.
        /// </summary>
        internal static string ReadingUserEnvVarsFrom {
            get {
                return ResourceManager.GetString("ReadingUserEnvVarsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read {0} variables:.
        /// </summary>
        internal static string ReadNumVariables {
            get {
                return ResourceManager.GetString("ReadNumVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set environment variables.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting user environment variable &apos;{0}&apos;\n\tto: &apos;{1}&apos;.
        /// </summary>
        internal static string SettingUserEnvVar {
            get {
                return ResourceManager.GetString("SettingUserEnvVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset environment variables.
        /// </summary>
        internal static string Unset {
            get {
                return ResourceManager.GetString("Unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name.
        /// </summary>
        internal static string VariableName {
            get {
                return ResourceManager.GetString("VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable value.
        /// </summary>
        internal static string VariableValue {
            get {
                return ResourceManager.GetString("VariableValue", resourceCulture);
            }
        }
    }
}
